#!/bin/sh
# postrm framework for openpanel packages
#
# see: dh_installdeb(1)

set -e

case "$1" in
    purge)
        update-rc.d openpanel-authd remove > /dev/null
        rm -f /var/opencore/log/authd.*
        ;;
esac

exit 0


