#!/bin/sh

set -e

case "$1" in
    remove)
        invoke-rc.d openpanel-authd stop || true
        rm -f /var/opencore/sockets/authd/authd.sock
    ;;

    upgrade|deconfigure|failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
#DEBHELPER#

exit 0


