#!/bin/sh

# This file is part of OpenPanel - The Open Source Control Panel
# OpenPanel is free software: you can redistribute it and/or modify it 
# under the terms of the GNU General Public License as published by the Free 
# Software Foundation, using version 3 of the License.
#
# Please note that use of the OpenPanel trademark may be subject to additional 
# restrictions. For more information, please visit the Legal Information 
# section of the OpenPanel website on http://www.openpanel.com/

TRANSACTION_ID="$1"
USERNAME=`echo "$2" | egrep "^..*$"`
if [ -z "$USERNAME" ]; then
  echo "Username not provided or too short"
  exit 1
fi
id "$USERNAME" 2>/dev/null | \
	egrep "groups=.*[[:digit:]]*(paneluser)" >/dev/null 2>&1 || {
	
  echo "User not in paneluser group"
  exit 1
}

PASSWORD="$3"
if [ -z "$PASSWORD" ]; then
  echo "Missing password"
  exit 1
fi

/usr/sbin/usermod -p "$PASSWORD" "$USERNAME"
