#!/bin/sh

# This file is part of OpenPanel - The Open Source Control Panel
# OpenPanel is free software: you can redistribute it and/or modify it 
# under the terms of the GNU General Public License as published by the Free 
# Software Foundation, using version 3 of the License.
#
# Please note that use of the OpenPanel trademark may be subject to additional 
# restrictions. For more information, please visit the Legal Information 
# section of the OpenPanel website on http://www.openpanel.com/

TRANSACTION_ID="$1"
USERNAME=`echo "$2" | egrep "^..*$"`
if [ -z "$USERNAME" ]; then
  echo "Username not provided or too short"
  exit 1
fi
id "$USERNAME" 2>/dev/null | \
	egrep "groups=.*[[:digit:]]*(openpaneluser)" >/dev/null 2>&1 || {
	
  echo "User [$USERNAME] not in openpaneluser group"
  exit 1
}

USERHOME=`eval echo ~$USERNAME`
FS=`df -P $USERHOME | tail -1 | awk '{print $6}'`

echo "$USERNAME $3 $4 0 0" | /usr/sbin/setquota -b $FS
