#!/bin/sh
TRANSACTION_ID="$1"
USERNAME=`echo "$2" | egrep "^..*$"`
if [ -z "$USERNAME" ]; then
  echo "Username not provided or too short"
  exit 1
fi
id "$USERNAME" 2>/dev/null | \
	egrep "groups=.*[[:digit:]]*(paneluser)" >/dev/null 2>&1 || {
	
  echo "User not in paneluser group"
  exit 1
}

PASSWORD="$3"
if [ -z "$PASSWORD" ]; then
  echo "Missing password"
  exit 1
fi

echo "$USERNAME:$PASSWORD" | /usr/sbin/chpasswd -e
