#!/bin/sh

# This file is part of OpenPanel - The Open Source Control Panel
# OpenPanel is free software: you can redistribute it and/or modify it 
# under the terms of the GNU General Public License as published by the Free 
# Software Foundation, using version 3 of the License.
#
# Please note that use of the OpenPanel trademark may be subject to additional 
# restrictions. For more information, please visit the Legal Information 
# section of the OpenPanel website on http://www.openpanel.com/

SERVICE=`echo "$1" | egrep "^[[:alnum:]]*$"`
if [ -z "$SERVICE" ]; then
  echo "No (valid) service specified"
  exit 1
fi
if [ ! -f /etc/init.d/$SERVICE ]; then
  echo "Service not found"
  exit 1
fi
ACTION="$2"
case "$ACTION" in
	0)
		exec chkconfig --level 345 $SERVICE off
		;;
	1)
		exec  chkconfig --level 345 $SERVICE on
		;;
	*)
		echo "Please use 0 or 1"
		exit 1
		;;
esac
