#!/bin/sh

# This file is part of OpenPanel - The Open Source Control Panel
# OpenPanel is free software: you can redistribute it and/or modify it 
# under the terms of the GNU General Public License as published by the Free 
# Software Foundation, using version 3 of the License.
#
# Please note that use of the OpenPanel trademark may be subject to additional 
# restrictions. For more information, please visit the Legal Information 
# section of the OpenPanel website on http://www.openpanel.com/

if [ -f /var/openpanel/conf/customize/user-homedirs ]; then
  . /var/openpanel/conf/customize/user-homedirs
else
  CUSTOMIZE_HASHING_LEVEL=0
  CUSTOMIZE_BASE_DIR=/home
fi
TRANSID="$1"
USERNAME=`echo "$2" | egrep "^..*$"`
if [ -z "$USERNAME" ]; then
  echo "Username not provided or too short"
  exit 1
fi
id "$USERNAME" >/dev/null 2>&1 && {
  echo "User already exists"
  exit 1
}

PASSWORD="$3"
if [ -z "$PASSWORD" ]; then
  echo "Missing password"
  exit 1
fi

if [ ! -d /var/openpanel/conf/rollback/$TRANSID ]; then
  mkdir /var/openpanel/conf/rollback/$TRANSID || {
    echo "Error creating rollback directory"
    exit 1
  }
fi
RBFILE="/var/openpanel/conf/rollback/$TRANSID/${USERNAME}.rollback"

HASH1=`echo "$USERNAME" | cut -c1`
HASH2=`echo "$USERNAME" | cut -c2`

case "$CUSTOMIZE_HASHING_LEVEL" in
  1)
	if [ ! -d "$CUSTOMIZE_BASE_DIR/${HASH1}" ]; then
          mkdir "$CUSTOMIZE_BASE_DIR/${HASH1}" || {
	    echo "mkdir failure"
	    exit 1
	  }
        fi
        HOMEDIR="$CUSTOMIZE_BASE_DIR/${HASH1}/$USERNAME"
	;;
  2)
        if [ ! -d "$CUSTOMIZE_BASE_DIR/${HASH1}" ]; then
          mkdir "$CUSTOMIZE_BASE_DIR/${HASH1}" || { 
	    echo "mkdir failure"
	    exit 1
	  }
        fi
        if [ ! -d "$CUSTOMIZE_BASE_DIR/${HASH1}/${HASH2}" ]; then
          mkdir "$CUSTOMIZE_BASE_DIR/${HASH1}/${HASH2}" || {
	    echo "mkdir failure"
	    exit 1
	  }
        fi
	HOMEDIR="$CUSTOMIZE_BASE_DIR/${HASH1}/${HASH2}/$USERNAME"
	;;
  *)
	HOMEDIR="$CUSTOMIZE_BASE_DIR/$USERNAME"
	;;
esac
# groupadd -r openpaneluser 2>/dev/null || true
/usr/sbin/useradd -m -d "$HOMEDIR" -G openpaneluser "$USERNAME" && \
	echo "MKUSER $USERNAME" > $RBFILE && \
	chmod 711 "$HOMEDIR" && \
	/usr/sbin/usermod -p "$PASSWORD" "$USERNAME"
