#!/bin/sh


# This file is part of OpenPanel - The Open Source Control Panel
# OpenPanel is free software: you can redistribute it and/or modify it 
# under the terms of the GNU General Public License as published by the Free 
# Software Foundation, using version 3 of the License.
#
# Please note that use of the OpenPanel trademark may be subject to additional 
# restrictions. For more information, please visit the Legal Information 
# section of the OpenPanel website on http://www.openpanel.com/

if [ -f /var/openpanel/conf/customize/user-homedirs ]; then
  . /var/openpanel/conf/customize/user-homedirs
else
  CUSTOMIZE_HASHING_LEVEL=0
  CUSTOMIZE_BASE_DIR=/home
fi

if [ -z "$CUSTOMIZE_ATTIC_DIR" ]; then
  CUSTOMIZE_ATTIC_DIR=$CUSTOMIZE_BASE_DIR/user.attic
fi

if [ ! -d "$CUSTOMIZE_ATTIC_DIR" ]; then
  mkdir "$CUSTOMIZE_ATTIC_DIR"
fi

TRANSACTION_ID="$1"
USERNAME=`echo "$2" | egrep "^..*$"`

if [ -z "$USERNAME" ]; then
  echo "Username not provided or too short"
  exit 1
fi

id "$USERNAME" 2>/dev/null || {
    # user doesn't exist, that's okay
    exit 0
}

id "$USERNAME" 2>/dev/null | \
	egrep "groups=.*[[:digit:]]*(openpaneluser)" >/dev/null 2>&1 || {
	
  echo "User not in openpaneluser group"
  exit 1
}

USERHOME=`eval echo ~$USERNAME`
if [ -d "$USERHOME" ]; then
  mv "$USERHOME" ${CUSTOMIZE_ATTIC_DIR}/${USERNAME} || { echo "attic-move failed"; exit 1; }
  chown root:root ${CUSTOMIZE_ATTIC_DIR}/${USERNAME} || { echo "attic-chown failed"; exit 1; }
  chmod 700 ${CUSTOMIZE_ATTIC_DIR}/${USERNAME} || { echo "attic-chmod failed"; exit 1; }
  find ${CUSTOMIZE_ATTIC_DIR}/${USERNAME} -user ${USERNAME} -exec chown root:root {} \;
fi

exec /usr/sbin/userdel "$USERNAME"
